name: Install TeX Live
description: Install a minimal TeX Live version and a customizable list of packages
inputs:
  package_file:
    description: 'A file listing the packages to install'
    required: false
  packages:
    description: 'Which packages to install'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/texlive.sh
      shell: sh
      working-directory: ${{ env.HOME }}
      env:
        TEXLIVE_PACKAGE_LIST_FILE: ${{ inputs.package_file }}
        TEXLIVE_PACKAGE_LIST: ${{ inputs.packages }}
