name: Install TeX Live
description: Install a minimal TeX Live version and a customizable list of packages
inputs:
  repository:
    description: 'The repository to install TeX Live from'
    required: false
  package_file:
    description: 'A file listing the packages to install'
    required: false
  packages:
    description: 'Which packages to install'
    required: false
  cache_version:
    description: 'A version number to allow forcing cache invalidation'
    default: 0
outputs:
  cache_key:
    description: "The updated or generated cache"
    value: ${{ steps.load-cache.outputs.cache-primary-key }}
runs:
  using: "composite"
  steps:
    - name: Get date
      shell: sh
      working-directory: ${{ env.HOME }}
      id: get-date
      run: |
        echo "date=$(date -I)" >> $GITHUB_OUTPUT
    - name: Load cache
      id: load-cache
      uses: actions/cache/restore@v3
      with:
        path: ~/texlive
        key: texlive-v${{ inputs.cache_version }}-${{ hashFiles(inputs.package_file) }}-${{ steps.get-date.outputs.date }}
        restore-keys: texlive-v${{ inputs.cache_version }}-${{ hashFiles(inputs.package_file) }}-
    - run: ${{ github.action_path }}/texlive.sh
      if: steps.load-cache.outputs.cache-hit != 'true'
      shell: sh
      working-directory: ${{ env.HOME }}
      env:
        TEXLIVE_REPOSITORY: ${{ inputs.repository }}
        TEXLIVE_PACKAGE_LIST_FILE: ${{ inputs.package_file }}
        TEXLIVE_PACKAGE_LIST: ${{ inputs.packages }}
    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: ~/texlive
        key: ${{ steps.load-cache.outputs.cache-primary-key }}
