name: Install TeX Live
description: Install a minimal TeX Live version and a customizable list of packages
inputs:
  repository:
    description: 'The repository to install TeX Live from'
    required: false
  package_file:
    description: 'A file listing the packages to install'
    required: false
  packages:
    description: 'Which packages to install'
    required: false
  cache_version:
    description: 'A version number to allow forcing cache invalidation'
    default: 0
runs:
  using: "composite"
  steps:
    - name: Generate unique ID
      shell: sh
      working-directory: ${{ env.HOME }}
      id: get-id
      run: |
        echo "id=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_OUTPUT
    - name: Load cache
      uses: actions/cache@v3
      with:
        path: ~/texlive
        key: texlive-v${{ inputs.cache_version }}-${{ steps.get-id.outputs.id }}
        restore-keys: texlive-v${{ inputs.cache_version }}-
    - run: ${{ github.action_path }}/texlive.sh
      shell: sh
      working-directory: ${{ env.HOME }}
      env:
        TEXLIVE_REPOSITORY: ${{ inputs.repository }}
        TEXLIVE_PACKAGE_LIST_FILE: ${{ inputs.package_file }}
        TEXLIVE_PACKAGE_LIST: ${{ inputs.packages }}
